#! /bin/sh
#
#
#	begin script CreateImage
#
#	author:	the Jake
#	born:	000713
#
#	part of CDMaker
#
#	purpose:	used to generate the actual ISO
#
#	modifications:
#		000719 - the Jake - including jget technique
#		011114 - the jake - began linking instead of copying files (speed)
#		030514 - jake - began adding misclz and miscql stuff
#					no real mods made though
#
#
#	CreateImage lz 0459

Usage()
{ 
	echo
	echo "Usage:  CreateImage CDTYPE CDNUM"
	echo
	echo "Example:  CreateImage lz 0459"
	echo
	return ; 
}


if [ -z "$CDROOT" -o -z "$bin" -o -z "$CDISOS" -o -z "$CDLTS" ]
then
        echo
        echo "  All necessary environment variables are not defined."
        echo "  Please review the script to see which need defined."
        echo
        exit 1
fi

if [ $# -ne 2 ]; then Usage; exit 1; fi

case $1 in
	qq|lz|ql|eit|final|misclz|miscql)
			TYPE=$1
			PRE=`jget $TYPE.PRE`
			CDID=`jget $TYPE.CDID`
			;;
	*)		Usage
			exit 1
			;;
esac

if [ -r $CDLTS/$TYPE.$2.list -a -s $CDLTS/$TYPE.$2.list ]
then
        CDNUM=$2
else
        echo "  ERROR:  List not found for $TYPE CD $2"
        Usage
        exit 1
fi

echo "  Creating cd image ... "
$bin/mkisofs -o $CDISOS/$PRE$CDNUM.iso -r -v -l -T -f -J -V $CDID$CDNUM $CDROOT

/usr/ucb/echo -n "Image Made:  " >> $STATUSLOG
date >> $STATUSLOG

#
#	end script CreateImage
#
