#! /bin/sh -a
#
#	begin script MakeCDImages
#
#	author:	the Jake
#	born:	000531
#	redesigned:	0007
#
#
#	I would like this to be run on a regular basis.
#	I am hoping that it will create CD Images without any input.
#	It will stay a few days behind the available data and
#	check for available disk space, never to create an image if 
# 	there is less than 1GB free on CDIMAGES
#	It will maintain log files of what it has done so that it
#	can reference them to see what it has to do.
#	It will also email me as it completes certain tasks.
#	The email thing may get annoying, but we'll see.
#
#	Requires the following environment variables to be set.
#		CDROOT	"the 'root' directory of the files to be put on CD
#		bin
#		OPERATOR
#
#	MAKE LOG ENTRY AND TO SCREEN AFTER ALMOST EVERYTHING
#	MAINTAIN LZ.LOG, QL.LOG AND EIT.LOG FILES
#
#	Modifications:
#	000622 - the Jake - added size check in LZ routine #000622
#	000705 - the Jake - beginning modifications for redesigned methods
#	000717 - the Jake - appears to be functioning properly with
#				just the EIT data.
#	000719 - the Jake - including jget technique
#	000726 - the Jake - very happy with the performance
#			currently functioning with all 3 types
#	000816 - the Jake - going to attempt to make it more mobile
#	011127 - the Jake - attempting to use external SizeToDo and DaysToDo (OK)
#	020301 - Jake - attempting to use external ftp-urania-size
#	020422 - jake - installed case statement to choose which CD type to start with
#	020620 - jake - added checks for $CDISOS and $CDSOURCE for after restore
#	021004 - Jake - added "final" data type for special CDs
#	030514 - jake - began adding miscql and misclz stuff
#


if [ -z "$bin" -o -z "$OPERATOR" ]
then
	echo
	echo "  All necessary environment variables are not defined."
	echo "  Please review the script to see which need defined."
	echo
	exit 1
fi

CDMAKER=`pwd`
CDISOS=$CDMAKER/CDIMAGES
CDROOT=$CDMAKER/CDSOURCE
CDLGS=$CDMAKER/CDLOGS
CDLTS=$CDMAKER/CDLISTS
CDSTATUS=$CDMAKER/CDSTATUS

if [ ! -d $CDISOS ]; then mkdir -p $CDISOS; fi		# 020620
if [ ! -d $CDROOT ]; then mkdir -p $CDROOT; fi		# 020620

echo
/usr/ucb/echo -n "Beginning CreateCDImages.sh : "
date

FREESPACE=`/bin/df -k $CDMAKER | gawk '{print $4}' | tail -1`

if [ $# -gt 0 ]; then
	case $1 in
		qq|lz|eit|ql|final|misclz|miscql)
			TYPE=$1;;
		*)  echo "TYPE $1 not found"
			exit 1;;
	esac
else
	TYPE="misclz"
fi

while [ $FREESPACE -gt 1000000 ]
do
	echo
	echo "------------------------------------------------------------"
	echo "  Freespace on $CDISOS is $FREESPACE kb."
	echo "------------------------------------------------------------"
	echo

	echo "  Checking $TYPE Status ...";	echo
	cd `jget $TYPE.DATA`

	DAYSTODO=`DaysToDo $TYPE`
	SIZETODO=`SizeToDo $TYPE`
	echo "  Currently $SIZETODO kb over $DAYSTODO days to do.";	echo

	if [ $DAYSTODO -gt `jget $TYPE.LAG` -a $SIZETODO -gt `jget LAGSIZE` ]
	then
#		CDNUM=`cat $CDLGS/$TYPE.log | gawk '{cdnum=$1} END {print cdnum}'`
		CDNUM=`tail -1 $CDLGS/$TYPE.log | gawk '{print $1}'`
		STATUSLOG=$CDSTATUS/$TYPE.$CDNUM.status




#	IF I'M PASSING ALL OF MY VARIABLES TO THESE SCRIPTS
#	AND I DON'T RUN THEM BY THEMSELVES,
#	WHY DO I SEND ARGUMENTS???????????

		case $TYPE in
			qq|lz|eit|ql)
				sh -a $CDMAKER/BuildCDList $TYPE
				;;
			miscql|misclz)
				sh -a $CDMAKER/BuildMiscList $TYPE		
				;;
		esac

		sh -a $CDMAKER/CopyCDFiles $TYPE $CDNUM
		sh -a $CDMAKER/CreateImage $TYPE $CDNUM

		/usr/ucb/mail -s "Made CD Image for $TYPE $CDNUM" $OPERATOR < /dev/null

		sudo sh -a $CDMAKER/VerifyISOFiles $TYPE $CDNUM





		#
		#	PUSH IMAGE TO URANIA TO FREE UP SPACE ON HERCULES
		#
		PRE=`jget $TYPE.PRE`
		ISONAME=$PRE$CDNUM.iso
		cd $CDISOS
		$bin/jpush $ISONAME urania	
		HerculesSize=`/bin/ls -l $ISONAME | gawk '{print $5}'`
		HerculesSize=${HerculesSize:-1}
		UraniaSize=`ftp-urania-size $ISONAME`
		UraniaSize=${UraniaSize:-0}

		if [ $HerculesSize -eq $UraniaSize ]
		then
			/bin/rm $ISONAME
			echo "  Moved $ISONAME to urania."
			/usr/ucb/echo -n "To Urania:   " >> $STATUSLOG
			date >> $STATUSLOG
			/usr/ucb/mail -s "Moved $ISONAME to urania.  Awaiting a burn." $OPERATOR < /dev/null
		fi

		sudo chown reduce:staff $STATUSLOG

	else
		echo "  $TYPE data is up to lagtime.  No $TYPE data will be processed.";	echo
		case $TYPE in
			qq) break;;
			final)	
				/usr/ucb/mail -s "Nothing left to do in MakeCDImages." $OPERATOR < /dev/null
				break ;;
			ql)	/usr/ucb/mail -s "Nothing left to do in MakeCDImages." $OPERATOR < /dev/null
				break ;;
			eit)	TYPE="ql";;
			lz)	TYPE="eit";;
			miscql)	TYPE="lz";;
			misclz)	TYPE="miscql";;
		esac
	fi

	ISONAME=""
	FREESPACE=`/bin/df -k $CDISOS | awk '{print $4}' | tail -1` 
done

if [ $FREESPACE -lt 1000000 ]
then
	echo "  Freespace has become limited.  I will not continue for now."
	/usr/ucb/mail -s "Freespace has become limited.  Ending MakeCDImages." $OPERATOR < /dev/null
fi

/usr/ucb/echo -n "Ending MakeCDImages.sh : "
date

#
#	end script MakeCDImages
#

