#! /bin/sh -a
#
#
#	begin script VerifyCDFiles
#
#	author:	the Jake
#	born:	000705
#
#	part of CDMaker
#
#	purpose:	Used to verify the existance of all the files that
#			are supposed to be on the CD.
#
#	modification:
#		000719 - the Jake - including jget technique
#
#		010130 - the Jake - Jukebox full of EIT
#			EIT to be done individually
#			from local CDROM drive.
#		010302 - the Jake - Jukebox full of LZ.
#			LZ and QL to be done locally.
#		030404 - jake - modified copy_jpeg and read_headers
#			so had to modify call
#		030515 - jake - adding misclz and miscql stuff
#
#	VerifyCDFiles lz 0457
#

Usage()
{
	echo
	echo "Usage:  VerifyCDFiles CDTYPE CDNUM"
	echo
	echo "Example:  VerifyCDFiles lz 0457"
	echo
	return;
}

CDLTS=$CDMAKER/CDLISTS

if [ $# -ne 2 ]; then Usage; exit 1; fi

case $1 in
	qq|lz|ql|eit|final)
			DIR=`jget $1.DIR`
			CDPATH="/cdrom/cdrom0/$DIR/level_05"
			;;
	misclz|miscql)
			DIR=`jget $1.DIR`
			CDPATH="/cdrom/cdrom0/$DIR/misc"
			;;
	*)		Usage
			exit 1			;;
esac

TYPE=$1
CDID=`jget $TYPE.cdid`
CDROOT="/cdrom/cdrom0/"

if [ -r $CDLTS/$TYPE.$2.list -a -s $CDLTS/$TYPE.$2.list ]
then
	CDNUM=$2
else
	echo "  ERROR:  List not found for $TYPE CD $2"
	Usage
	exit 1
fi


echo "  Copying jpgs, Reading headers and reviewing content..."

copy_jpegs 	#	$TYPE $CDNUM	# 030404
read_headers 	#	$TYPE $CDNUM	# 030404

cd $CDPATH

case $TYPE in
	qq|lz|ql|eit|final)
		ls -1d */*/*fts | gawk -F. '{print $1}' > $CDLTS/tempcd.list
		;;
	misclz|miscql)
		ls -1d */*/9* 2> /dev/null | sort -t / -k 3 | gawk -F. '{print $1}' > $CDLTS/tempcd.list 
		ls -1d */*/[012]* 2> /dev/null | sort -t / -k 3 | gawk -F. '{print $1}' >> $CDLTS/tempcd.list
		#	this verification for the misc data is not
		#	as good as that for standard data
		;;
esac

if [ -z "`diff $CDLTS/$TYPE.$CDNUM.list $CDLTS/tempcd.list`" ]
then
	echo "  No difference between existing and expected files."
	echo
else
	echo "  ERROR: Difference between existing and expected files:"
	diff $CDLTS/$TYPE.$CDNUM.list $CDLTS/tempcd.list
fi

STATUSLOG=$CDMAKER/CDSTATUS/$TYPE.$CDNUM.status
/usr/ucb/echo -n "Verified:    " >> $STATUSLOG
date >> $STATUSLOG

cd $CDMAKER
eject
exit	#	Clean Exit

#
#	end script VerifyCDFiles
#
