/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SwingApplication */

#ifndef _Included_SwingApplication
#define _Included_SwingApplication
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: labelPrefix */
/*
 * Class:     SwingApplication
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SwingApplication_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
