/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MakeFITSGUI */

#ifndef _Included_MakeFITSGUI
#define _Included_MakeFITSGUI
#ifdef __cplusplus
extern "C" {
#endif
#undef MakeFITSGUI_FOCUS_TRAVERSABLE_UNKNOWN
#define MakeFITSGUI_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef MakeFITSGUI_FOCUS_TRAVERSABLE_DEFAULT
#define MakeFITSGUI_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef MakeFITSGUI_FOCUS_TRAVERSABLE_SET
#define MakeFITSGUI_FOCUS_TRAVERSABLE_SET 2L
/* Inaccessible static: focusTraversalKeyPropertyNames */
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef MakeFITSGUI_TOP_ALIGNMENT
#define MakeFITSGUI_TOP_ALIGNMENT 0.0f
#undef MakeFITSGUI_CENTER_ALIGNMENT
#define MakeFITSGUI_CENTER_ALIGNMENT 0.5f
#undef MakeFITSGUI_BOTTOM_ALIGNMENT
#define MakeFITSGUI_BOTTOM_ALIGNMENT 1.0f
#undef MakeFITSGUI_LEFT_ALIGNMENT
#define MakeFITSGUI_LEFT_ALIGNMENT 0.0f
#undef MakeFITSGUI_RIGHT_ALIGNMENT
#define MakeFITSGUI_RIGHT_ALIGNMENT 1.0f
#undef MakeFITSGUI_serialVersionUID
#define MakeFITSGUI_serialVersionUID -7644114512714619750LL
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseWheelListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
#undef MakeFITSGUI_serialVersionUID
#define MakeFITSGUI_serialVersionUID 4613797578919906343LL
/* Inaccessible static: dbg */
#undef MakeFITSGUI_INCLUDE_SELF
#define MakeFITSGUI_INCLUDE_SELF 1L
#undef MakeFITSGUI_SEARCH_HEAVYWEIGHTS
#define MakeFITSGUI_SEARCH_HEAVYWEIGHTS 1L
/* Inaccessible static: class_00024java_00024awt_00024Container */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ContainerListener */
/* Inaccessible static: readObjectCallbacks */
/* Inaccessible static: managingFocusForwardTraversalKeys */
/* Inaccessible static: managingFocusBackwardTraversalKeys */
/* Inaccessible static: suppressDropSupport */
/* Inaccessible static: checkedSuppressDropSupport */
#undef MakeFITSGUI_WHEN_FOCUSED
#define MakeFITSGUI_WHEN_FOCUSED 0L
#undef MakeFITSGUI_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define MakeFITSGUI_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef MakeFITSGUI_WHEN_IN_FOCUSED_WINDOW
#define MakeFITSGUI_WHEN_IN_FOCUSED_WINDOW 2L
#undef MakeFITSGUI_UNDEFINED_CONDITION
#define MakeFITSGUI_UNDEFINED_CONDITION -1L
#undef MakeFITSGUI_IS_DOUBLE_BUFFERED
#define MakeFITSGUI_IS_DOUBLE_BUFFERED 0L
#undef MakeFITSGUI_ANCESTOR_USING_BUFFER
#define MakeFITSGUI_ANCESTOR_USING_BUFFER 1L
#undef MakeFITSGUI_IS_PAINTING_TILE
#define MakeFITSGUI_IS_PAINTING_TILE 2L
#undef MakeFITSGUI_IS_OPAQUE
#define MakeFITSGUI_IS_OPAQUE 3L
#undef MakeFITSGUI_KEY_EVENTS_ENABLED
#define MakeFITSGUI_KEY_EVENTS_ENABLED 4L
#undef MakeFITSGUI_FOCUS_INPUTMAP_CREATED
#define MakeFITSGUI_FOCUS_INPUTMAP_CREATED 5L
#undef MakeFITSGUI_ANCESTOR_INPUTMAP_CREATED
#define MakeFITSGUI_ANCESTOR_INPUTMAP_CREATED 6L
#undef MakeFITSGUI_WIF_INPUTMAP_CREATED
#define MakeFITSGUI_WIF_INPUTMAP_CREATED 7L
#undef MakeFITSGUI_ACTIONMAP_CREATED
#define MakeFITSGUI_ACTIONMAP_CREATED 8L
#undef MakeFITSGUI_CREATED_DOUBLE_BUFFER
#define MakeFITSGUI_CREATED_DOUBLE_BUFFER 9L
#undef MakeFITSGUI_CREATED_VOLATILE_DOUBLE_BUFFER
#define MakeFITSGUI_CREATED_VOLATILE_DOUBLE_BUFFER 10L
#undef MakeFITSGUI_IS_PRINTING
#define MakeFITSGUI_IS_PRINTING 11L
#undef MakeFITSGUI_IS_PRINTING_ALL
#define MakeFITSGUI_IS_PRINTING_ALL 12L
#undef MakeFITSGUI_IS_REPAINTING
#define MakeFITSGUI_IS_REPAINTING 13L
#undef MakeFITSGUI_WRITE_OBJ_COUNTER_FIRST
#define MakeFITSGUI_WRITE_OBJ_COUNTER_FIRST 14L
#undef MakeFITSGUI_RESERVED_1
#define MakeFITSGUI_RESERVED_1 15L
#undef MakeFITSGUI_RESERVED_2
#define MakeFITSGUI_RESERVED_2 16L
#undef MakeFITSGUI_RESERVED_3
#define MakeFITSGUI_RESERVED_3 17L
#undef MakeFITSGUI_RESERVED_4
#define MakeFITSGUI_RESERVED_4 18L
#undef MakeFITSGUI_RESERVED_5
#define MakeFITSGUI_RESERVED_5 19L
#undef MakeFITSGUI_RESERVED_6
#define MakeFITSGUI_RESERVED_6 20L
#undef MakeFITSGUI_WRITE_OBJ_COUNTER_LAST
#define MakeFITSGUI_WRITE_OBJ_COUNTER_LAST 21L
#undef MakeFITSGUI_REQUEST_FOCUS_DISABLED
#define MakeFITSGUI_REQUEST_FOCUS_DISABLED 22L
/* Inaccessible static: class_00024javax_00024swing_00024JComponent_00024KeyboardState */
/* Inaccessible static: class_00024javax_00024swing_00024event_00024AncestorListener */
/* Inaccessible static: class_00024java_00024beans_00024VetoableChangeListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
/* Inaccessible static: settingsFile */
/* Inaccessible static: fcDirIMG */
/* Inaccessible static: fcDirOut */
/* Inaccessible static: fcDirIn */
/*
 * Class:     MakeFITSGUI
 * Method:    getIMGSize
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MakeFITSGUI_getIMGSize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     MakeFITSGUI
 * Method:    addKey
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_MakeFITSGUI_addKey
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     MakeFITSGUI
 * Method:    showKey
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_MakeFITSGUI_showKey
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     MakeFITSGUI
 * Method:    fitsCopy
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_MakeFITSGUI_fitsCopy
  (JNIEnv *, jobject, jstring, jstring, jint, jint);

/*
 * Class:     MakeFITSGUI
 * Method:    fitsCopyOffset
 * Signature: (Ljava/lang/String;Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_MakeFITSGUI_fitsCopyOffset
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint);

/*
 * Class:     MakeFITSGUI
 * Method:    readFooter
 * Signature: (Ljava/lang/String;Ljava/lang/String;IIII)I
 */
JNIEXPORT jint JNICALL Java_MakeFITSGUI_readFooter
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jint);

/*
 * Class:     MakeFITSGUI
 * Method:    getKeywordCount
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_MakeFITSGUI_getKeywordCount
  (JNIEnv *, jobject, jstring);

/*
 * Class:     MakeFITSGUI
 * Method:    readFITSKeyNum
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MakeFITSGUI_readFITSKeyNum
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
